### ISSUE TITLE
Print a warning when an interrupted running status occurs

### ISSUE THREAD

**Issue by truj** [jazz-soft/test-midi-files#11]
Some MIDI files use running status, interrupted by a Meta or SysEx event.
E.g. this sequence:
- Channel event with status byte
- (optional) more channel events **without** status byte (using running status)
- Meta or SysEx event
- event **without** status byte

According to the SMF specification this behaviour is forbidden.
The spec says: "**Sysex events and meta-events cancel any running status which was in effect.**"

However most software (including yours) is tolerant enough to use the only useful interpretation: re-using the running status that was valid before the Meta or SysEx event.

But from **test-midi-files** I would expect a warning if an interrupted running status is found.
So far this is not the case.

There is notable software available that interprets such events differently - including fluidsynth and Java.
I have [fixed this issue in Java](https://github.com/openjdk/jdk/pull/16546), but older Java versions are still affected.

So a warning would really make sense.

**Comment by jazz-soft** [comment]
Thanks! That's a good idea for a new test to add!

**Comment by jazz-soft** [comment]
FYI: I've added two tests in this repository. To print the warning I need to modify https://github.com/jazz-soft/JZZ-midi-SMF

**Comment by truj** [comment]
Thank you, the warning works now. :+1:
