### ISSUE TITLE
The notes in test-c-major-scale.mid are one octave lower than claimed

### ISSUE THREAD

**Issue by Malcohol** [jazz-soft/test-midi-files#3]
This file seems to contain a major scale from C4 to C5, rather than a major scale from C5 to C6 as claimed.

I've looked parsed the file with my own code, opened it in Ardour and checked the data with a hex editor. The first note value is 60 (C4) rather than 72 (C5).

**Comment by jazz-soft** [comment]
Different software can number octaves in different way.
In JZZ and related products, the lowest octave is 0 to avoid negative numbers.

**Comment by Malcohol** [comment]
Ok. This discussion confirms what you say:
https://www.midi.org/midi/forum/830-midi-octave-and-note-numbering-standard

It's a minor point, but given that the generated midi files are in a sense "outside" your project's codebase, it might be preferable to avoid using the ambiguous note naming within the midi files.

**Comment by jazz-soft** [comment]
Any naming would be ambiguous:
`For MIDI, middle C is always note number 60 even though it may be another pitch or described by a different octave designation - C3, C4 or C5.`
