### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by duhrer** [jazz-soft/test-midi-files#8]
Hugely interested in using this to test my work, I was wondering if you're wiling to publish it via `npm` so I can consume it that way?

**Comment by jazz-soft** [comment]
Hi! Thanks for asking!
This is just a set of MIDI files, not much of a JavaScript module to `import` or `require()`.
I'm not sure how to publish it via npm or if that is a good idea at all.
You are free to copy any relevant files to your project.
Why would you need to have them as an npm module?

**Comment by duhrer** [comment]
I usually prefer to keep a repository focused on the unique value it adds.  It also makes attribution clearer, i.e. this thing I use in my project is something someone else wrote.

I'll do as you suggest and copy what I need along with license and attribution details.  Thanks again for providing the package.

**Comment by Malcohol** [comment]
If you just need the contents at build/test time (as opposed to runtime) then consider consuming the project as a git submodule. It's working well for me anyway :)

**Comment by jazz-soft** [comment]
Published... Finally :)
